import {
  TicketType,
  TicketTypeInsert,
  UserType,
} from "@/supabase/functions/common/schema"

export const tickets: TicketType[] = [
  {
    id: "1",
    user_id: "user_01",
    title: "Review Financial Statements",
    description: "Conduct a review of the quarterly financial statements.",
    target_department: "financial",
    source_department: "main office",
    status: "fulfilled",
    fulfill_message: "All statements are accurate and complete.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "2",
    user_id: "user_02",
    title: "Design New Marketing Materials",
    description:
      "Create new brochures and flyers for the upcoming product launch.",
    target_department: "design",
    source_department: "marketing",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "3",
    user_id: "user_03",
    title: "Upgrade Engineering Tools",
    description:
      "Propose and implement new software tools for the engineering team.",
    target_department: "engineering",
    source_department: "main office",
    status: "rejected",
    fulfill_message: null,
    reject_message: "Budget constraints prevent the upgrade.",
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "4",
    user_id: "user_04",
    title: "Conduct Market Research",
    description: "Analyze customer feedback and market trends.",
    target_department: "marketing",
    source_department: "financial",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "5",
    user_id: "user_05",
    title: "Develop New Product Prototypes",
    description:
      "Create prototypes for the next generation of our product line.",
    target_department: "engineering",
    source_department: "design",
    status: "fulfilled",
    fulfill_message: "Prototypes successfully developed and tested.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "6",
    user_id: "user_06",
    title: "Prepare Annual Budget Report",
    description:
      "Compile and present the budget report for the next fiscal year.",
    target_department: "financial",
    source_department: "main office",
    status: "rejected",
    fulfill_message: null,
    reject_message: "Incomplete data provided by departments.",
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "7",
    user_id: "user_07",
    title: "Redesign Company Website",
    description: "Implement a new design for the company website.",
    target_department: "design",
    source_department: "marketing",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "8",
    user_id: "user_08",
    title: "Optimize Manufacturing Process",
    description: "Analyze and improve the current manufacturing process.",
    target_department: "engineering",
    source_department: "main office",
    status: "fulfilled",
    fulfill_message: "Process optimized with a 15% efficiency gain.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "9",
    user_id: "user_09",
    title: "Create Social Media Strategy",
    description:
      "Develop a comprehensive social media strategy for the next quarter.",
    target_department: "marketing",
    source_department: "main office",
    status: "rejected",
    fulfill_message: null,
    reject_message: "The strategy lacks clear KPIs.",
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "10",
    user_id: "user_10",
    title: "Evaluate New Software Vendors",
    description: "Assess potential software vendors for the IT department.",
    target_department: "engineering",
    source_department: "financial",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "11",
    user_id: "user_11",
    title: "Plan Office Relocation",
    description:
      "Coordinate the relocation of the main office to a new building.",
    target_department: "main office",
    source_department: "financial",
    status: "fulfilled",
    fulfill_message: "Relocation completed successfully.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "12",
    user_id: "user_12",
    title: "Launch New Advertising Campaign",
    description: "Roll out a new advertising campaign for the latest product.",
    target_department: "marketing",
    source_department: "design",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "13",
    user_id: "user_13",
    title: "Audit Department Expenses",
    description:
      "Perform a detailed audit of departmental expenses for the past year.",
    target_department: "financial",
    source_department: "main office",
    status: "fulfilled",
    fulfill_message: "Audit completed with no discrepancies found.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "14",
    user_id: "user_14",
    title: "Design New Company Logo",
    description: "Create a modern and versatile logo for the company.",
    target_department: "design",
    source_department: "marketing",
    status: "rejected",
    fulfill_message: null,
    reject_message: "The logo did not meet the branding requirements.",
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "15",
    user_id: "user_15",
    title: "Enhance IT Security Protocols",
    description: "Update and strengthen the company's IT security protocols.",
    target_department: "engineering",
    source_department: "main office",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "16",
    user_id: "user_16",
    title: "Finalize Partnership Agreement",
    description:
      "Negotiate and finalize the partnership agreement with a key vendor.",
    target_department: "financial",
    source_department: "main office",
    status: "fulfilled",
    fulfill_message: "Partnership agreement successfully finalized.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "17",
    user_id: "user_17",
    title: "Improve Customer Support Process",
    description: "Analyze and improve the customer support workflow.",
    target_department: "main office",
    source_department: "engineering",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "18",
    user_id: "user_18",
    title: "Update Financial Projections",
    description:
      "Reassess and update the financial projections for the next quarter.",
    target_department: "financial",
    source_department: "main office",
    status: "rejected",
    fulfill_message: null,
    reject_message: "Projections based on outdated data.",
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "19",
    user_id: "user_19",
    title: "Launch Employee Training Program",
    description: "Develop and launch a training program for new employees.",
    target_department: "main office",
    source_department: "engineering",
    status: "fulfilled",
    fulfill_message: "Training program launched successfully.",
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "20",
    user_id: "user_20",
    title: "Redesign Office Layout",
    description: "Plan and execute the redesign of the office layout.",
    target_department: "design",
    source_department: "main office",
    status: "processing",
    fulfill_message: null,
    reject_message: null,
    pictures: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
]
